//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d3Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bouquet
    {
        public string BouquetPrefix { get; set; }
        public string BouquetName { get; set; }
        public string LUCBouquetType { get; set; }
        public string LUCBouquetStatus { get; set; }
        public string BouquetCompatibility { get; set; }
        public string SMSText { get; set; }
        public Nullable<System.Guid> FileRef { get; set; }
        public string Email { get; set; }
        public string EmailSubject { get; set; }
        public string EmailTemplate { get; set; }
        public string HTML { get; set; }
        public string WebAddress { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.Guid> InsertedBy { get; set; }
        public string InsertedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public System.Guid GenisysID { get; set; }
        public Nullable<int> LegacyProductID { get; set; }
        public bool IsCashbackBouquet { get; set; }
        public Nullable<decimal> PointsValue { get; set; }
        public string AttachedBehaviourDefinition { get; set; }
        public string OnlineFormXML { get; set; }
        public int WelcomePackSendTypeId { get; set; }
    }
}
