//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d3Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeniSysEntities : DbContext
    {
        public GeniSysEntities()
            : base("name=GeniSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Policy> Policy { get; set; }
        public virtual DbSet<Bouquet> Bouquet { get; set; }
        public virtual DbSet<LookUpCodes> LookUpCodes { get; set; }
    
        public virtual ObjectResult<proc_GPTest_GetProductCount_Result> proc_GPTest_GetProductCount(string bouquetType)
        {
            var bouquetTypeParameter = bouquetType != null ?
                new ObjectParameter("BouquetType", bouquetType) :
                new ObjectParameter("BouquetType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GPTest_GetProductCount_Result>("proc_GPTest_GetProductCount", bouquetTypeParameter);
        }
    }
}
