//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d3Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUpCodes
    {
        public string LUCLookUpType { get; set; }
        public string LookUpCode { get; set; }
        public string Description { get; set; }
        public Nullable<short> SequenceNo { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public string DeletedByName { get; set; }
        public bool SystemField { get; set; }
        public System.Guid GenisysID { get; set; }
        public string LookUpRules { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ClaimsSpecific { get; set; }
    }
}
